### ISSUE TITLE
pos out of range error when attempting to extract anything from an HFS+ volume

### ISSUE THREAD

**Issue by fouram** [unsound/hfsexplorer#14] opened 2021-04-03 04:03 UTC
Not sure if I'm doing something wrong, or if something is wrong with this disk, but any file I attempt to extract, I get the following error:

java.lang.IllegalArgumentException: pos out of range (pos=28097597440,virtualLength=4042448896)
	at org.catacombae.hfs.io.ReadableBlockCachingStream.seek(ReadableBlockCachingStream.java:114)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.seek(SynchronizedReadableRandomAccessStream.java:215)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.readFrom(SynchronizedReadableRandomAccessStream.java:94)
	at org.catacombae.io.ReadableRandomAccessSubstream.read(ReadableRandomAccessSubstream.java:82)
	at org.catacombae.hfs.io.ForkFilter.read(ForkFilter.java:358)
	at org.catacombae.hfs.io.ForkFilter.readFully(ForkFilter.java:413)
	at org.catacombae.hfs.io.ForkFilter.readFully(ForkFilter.java:403)
	at org.catacombae.hfs.plus.HFSPlusVolume.readNodeDescriptor(HFSPlusVolume.java:238)
	at org.catacombae.hfs.BTreeFile.readNodeDescriptor(BTreeFile.java:239)
	at org.catacombae.hfs.BTreeFile$BTreeFileSession.<init>(BTreeFile.java:63)
	at org.catacombae.hfs.AttributesFile$Session.<init>(AttributesFile.java:44)
	at org.catacombae.hfs.AttributesFile$Session.<init>(AttributesFile.java:44)
	at org.catacombae.hfs.AttributesFile.openSession(AttributesFile.java:86)
	at org.catacombae.hfs.BTreeFile.getRootNode(BTreeFile.java:265)
	at org.catacombae.hfsexplorer.gui.BTreeInfoPanel.<init>(BTreeInfoPanel.java:83)
	at org.catacombae.hfsexplorer.gui.AttributesInfoPanel.<init>(AttributesInfoPanel.java:42)
	at org.catacombae.hfsexplorer.VolumeInfoWindow.<init>(VolumeInfoWindow.java:163)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$8.actionPerformed(FileSystemBrowserWindow.java:420)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by unsound** [comment] 2021-09-26 18:35
Late reply but this looks like the partition, disk or image is incomplete, e.g. the length of the image may be 4042448896 bytes (4 GB-ish) but the requested offset is at around 28 GB.
I'm actually a little suspicious about this since a number around the 4 GB mark could indicate a bug caused by 32-bit truncation of a 64-bit value somewhere in the code. However I'd need some way to reproduce this, and Java uses signed 32-bit values anyway which makes this less likely.

**Comment by lovetoflyguy** [comment] 2021-09-29 20:39
I am also seeing this error.
Windows 10 v.21H1
HFSExplorer 2021.2.22 (portable)
JRE: 1.8.0_301
Extracting from portable HDD via USB to network share (as Domain Admin)

java.lang.IllegalArgumentException: pos out of range (pos=35737141248,virtualLength=4149903360)
	at org.catacombae.hfs.io.ReadableBlockCachingStream.seek(ReadableBlockCachingStream.java:114)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.seek(SynchronizedReadableRandomAccessStream.java:215)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.readFrom(SynchronizedReadableRandomAccessStream.java:94)
	at org.catacombae.io.ReadableRandomAccessSubstream.read(ReadableRandomAccessSubstream.java:82)
	at org.catacombae.hfs.io.ForkFilter.read(ForkFilter.java:358)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.extractForkToStream(FileSystemBrowserWindow.java:1126)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.extractEntry(FileSystemBrowserWindow.java:2323)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.access$1600(FileSystemBrowserWindow.java:122)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$ExtractVisitor.file(FileSystemBrowserWindow.java:2794)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.traverseTreeRecursive(FileSystemBrowserWindow.java:1732)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.traverseTree(FileSystemBrowserWindow.java:1656)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.extract(FileSystemBrowserWindow.java:1925)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$20.run(FileSystemBrowserWindow.java:1550)
	at java.lang.Thread.run(Unknown Source)

**Comment by lovetoflyguy** [comment] 2021-09-29 20:54
Also happens when using the installed version of HFSExplorer (v.2021.2.22)
JRE: 1.8.0_301 (x86 & x64 installed)

An unhandled exception occurred when extracting to file "C:\Users\me\Documents\1- Dark Horse.tiff":
java.lang.IllegalArgumentException: pos out of range (pos=35528155136,virtualLength=4149903360)
	at org.catacombae.hfs.io.ReadableBlockCachingStream.seek(ReadableBlockCachingStream.java:114)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.seek(SynchronizedReadableRandomAccessStream.java:215)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.readFrom(SynchronizedReadableRandomAccessStream.java:94)
	at org.catacombae.io.ReadableRandomAccessSubstream.read(ReadableRandomAccessSubstream.java:82)
	at org.catacombae.hfs.io.ForkFilter.read(ForkFilter.java:358)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.extractForkToStream(FileSystemBrowserWindow.java:1126)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.extractEntry(FileSystemBrowserWindow.java:2323)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.access$1600(FileSystemBrowserWindow.java:122)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$ExtractVisitor.file(FileSystemBrowserWindow.java:2794)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.traverseTreeRecursive(FileSystemBrowserWindow.java:1732)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.traverseTree(FileSystemBrowserWindow.java:1656)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.extract(FileSystemBrowserWindow.java:1925)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$20.run(FileSystemBrowserWindow.java:1550)
	at java.lang.Thread.run(Unknown Source)
[WARNING] org.catacombae.io.SynchronizedReadableRandomAccessStream@1b87e2a is garbage collected with 2 remaining references.

File info:
![Clipboard010](https://user-images.githubusercontent.com/3149904/135346929-29b2c0e0-174d-4940-b7d1-6381b3f56ba1.png)

**Comment by lovetoflyguy** [comment] 2021-09-29 21:29
The HDD opens perfectly fine in MacOS, so I'm sure that the partition/files are not corrupt.

I hope this input helps.

**Comment by unsound** [comment] 2021-09-30 04:06
In order to troubleshoot this I would need some additional data:

- Open `C:\Program Files (x86)\HFSExplorer\bin` in Explorer, right-click `dumpfsdata.bat` and choose to run it as administrator (to enable device access).
- Choose the the `Partition0` entry of problematic HDD and click "Load".
- Choose the partition of the HFS+ volume.

Now some files will be extracted. Make note of where they are extracted to and attach these files to this issue, or send them directly to me if you don't want data from your hard drive publicly accessible (it's the first and last 64 KiB of the HFS+ volume).

**Comment by lovetoflyguy** [comment] 2021-09-30 14:14
Files attached.
[fsdump.zip](https://github.com/unsound/hfsexplorer/files/7260141/fsdump.zip)
.

**Comment by unsound** [comment] 2021-09-30 17:26
@lovetoflyguy Thanks, that was helpful and I think I found the problem. I've pushed a fix to the 'proposed' branch. Let me know how it works for you (and also if you need help building the code to test the fix).

**Comment by lovetoflyguy** [comment] 2021-09-30 20:44
@unsound Glad I could help! It looks like I'm going to need some help with building the code - it's been far too long since I worked with Netbeans.

**Comment by unsound** [comment] 2021-10-01 03:10
@lovetoflyguy Basically all you need is a JDK (any JDK should work unless it's really ancient... I prefer the Adoptium JDKs myself: https://adoptium.net/) and Apache Ant (https://ant.apache.org/). Once you've configured your `PATH` environment variable so that `javac` and `ant` can be used from a command line you can just issue `ant build-all` which builds the jar file `dist\lib\hfsx.jar` which you can drop into place in your existing HFSExplorer installation (e.g. in `C:\Program Files (x86)\HFSExplorer\lib`) or you can just run the software right away from the development directory with `hfsexplorer.bat`.

Alternatively for your convenience I'm attaching a fresh build from my build setup:
[hfsx.jar.zip](https://github.com/unsound/hfsexplorer/files/7263820/hfsx.jar.zip)

**Comment by lovetoflyguy** [comment] 2021-10-01 22:05
Thanks! That's not working for me, though. When replacing the jar in my installed and existing portable locations, I get a launch error: could not find the required class files, and a Java exception error, but the app still runs but does not detect any HFS+ partitions.

**Comment by unsound** [comment] 2021-10-02 02:24
@lovetoflyguy Ah, I forgot that you also have to update `csframework.jar` because of dependencies. It's built and available in the git repository:
https://github.com/unsound/hfsexplorer/blob/master/dist/lib/csframework.jar

**Comment by lovetoflyguy** [comment] 2021-10-05 14:48
Thanks! That seems to have done the trick, I am now able to export files from the HDD successfully.

**Comment by unsound** [comment] 2021-10-05 14:55
Awesome! Although @fouram, the original reporter has not responded I will close this since it's quite likely the same issue. If the latest fixes aren't solving it for others we can reopen this.

**Closed by unsound** 2021-10-05 14:55 UTC
Labels: bug
