### ISSUE TITLE
Feature request: HiDPI support

### ISSUE THREAD

**Issue by Sunspark-007** [unsound/hfsexplorer#28] opened 2021-10-26 20:46 UTC
The app appears to have been designed for 96 dpi. The HiDPI compatibility setting Application will allow for crisp sharp text but rows are then displayed too close to each other so the bottom portion of text is cut off. System or System (Enhanced) setting doesn't have the issue of text being cut off but text then appears blurry.

**Comment by unsound** [comment] 2021-11-04 07:08
Closing this as no there has been no further information shared about the problem. Most likely the problem is caused by an older Java version and solved by a newer one. If there are still issues that aren't solved by updating Java, then please reopen with more info.

**Closed by unsound** 2021-11-04 07:08 UTC
